"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const taskController_1 = require("../controllers/taskController");
const auth_1 = require("../middlewares/auth");
const router = (0, express_1.Router)();
router.use(auth_1.authenticate);
router.get('/', taskController_1.getTasks);
router.get('/:id', taskController_1.getTask);
router.post('/', auth_1.requireAdmin, taskController_1.createTask);
router.put('/:id', auth_1.requireAdmin, taskController_1.updateTask);
router.delete('/:id', auth_1.requireAdmin, taskController_1.deleteTask);
router.post('/:id/comment', taskController_1.addComment);
router.post('/:id/history', taskController_1.addHistory);
exports.default = router;
